### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by PJ-Finlay** [PJ-Finlay/tinytranslate#4]
```
tinytranslate$ python translate.py 
loss 5.54 accuracy 0.00:   1%|▊                                                                                   | 1/100 [00:07<12:38,  7.66s/it]
Traceback (most recent call last):
  File "/home/pj/Desktop/Tinygrad/tinytranslate/translate.py", line 100, in <module>
    train(model, X_train, Y_train, optim, TRAIN_STEPS, BS=64)
  File "/home/pj/Desktop/Tinygrad/tinygrad/extra/training.py", line 31, in train
    loss, accuracy = train_step(x, y)
  File "/home/pj/Desktop/Tinygrad/tinygrad/tinygrad/jit.py", line 86, in __call__
    self.input_replace = get_input_replace(self.jit_cache, input_rawbuffers)
  File "/home/pj/Desktop/Tinygrad/tinygrad/tinygrad/jit.py", line 25, in get_input_replace
    assert len(set(input_replace.values())) == len(input_rawbuffers), "some input tensors not found"
AssertionError: some input tensors not found
```

**Comment by PJ-Finlay** [comment]
Tinytranslate is working again! I just installed the latest [tinygrad](https://github.com/tinygrad/tinygrad), ran the demo in the README, and it's working.

I'm not sure exactly what the previous issue was but I this [bug](https://github.com/tinygrad/tinygrad/issues/2829) was the root cause.
